proc contents data= sasdata.cpi_data; run;
DATA work.cpi;
	SET sasdata.cpi_data;
run;
DATA work.cpi2;
	SET work.cpi;
	VALUE2 = VALUE*4;
run;
DATA work.cpi2;
	SET work.cpi2;
	VALUE3 = VALUE**3;
	VALUE4 = VALUE/12;
	VALUE5 = log(VALUE);
run;
DATA work.cpi3;
	SET work.cpi2;
	IF VALUE > 100 THEN VAR1 = VALUE;
		ELSE VAR1 = 0;
	LENGTH VAR2 $10;
	IF (100 <= VALUE <=150) THEN VAR2 = "CHK";
	IF ((50 <= VALUE <= 75) OR (125 <= VALUE <= 175)) THEN VAR3 = 1; 
		ELSE VAR3 = 0;
	IF FIRST.VALUE then OBSNUM = 1;
		ELSE OBSNUM+1;
run;
DATA work.cpi3;
	SET work.cpi3;
	DOLLVAL = VALUE;
	format DOLLVAL dollar10.2;
	NEWDATE = DATE;
	format NEWDATE MMDDYYS10.;
run;		
PROC CONTENTS data=work.cpi3;
run;

data Sasdata.Assignment1;
	SET work.cpi3;
run;
data Sasdata.Assignment1;
	SET Sasdata.Assignment1;
	IF VALUE > 200 THEN delete;
run;
proc print data=Sasdata.Assignment1;
	var DATE VALUE;
	where VALUE < 13;
run;
proc means data=Sasdata.Assignment1 Mean Median Sum Min Max;
	var VALUE;
	where DATE BETWEEN mdy(01,01,1950) AND mdy(12,31,1959);
data Sasdata.Assignment1;
	SET Sasdata.Assignment1;
	IF VALUE = 14 OR VALUE = 24.4 OR VALUE = 133.8 OR VALUE = 201.4 THEN COUNT = 1;
	ELSE COUNT = 0;
run;

